apiVersion: v1
kind: Pod
metadata:
  name: ribak-volodya
  namespace: homework
spec:
  volumes:
  - name: shared-dir
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  containers:
  - name: web-server
    image: nginx:1.14.2
    ports:
    - containerPort: 8000
    volumeMounts:
    - mountPath: /homework
      name: shared-dir
    - mountPath: /etc/nginx/conf.d
      name: nginx-config-volume
    lifecycle:
      preStop:
        exec:
          command: ['sh', 'c', 'rm -f /homework/index.html']
  initContainers:
  - name: download-index
    image: busybox:1.28
    command: ['sh', '-c', 'wget http://example.com/ -P /init']
    volumeMounts:
      - mountPath: /init
        name: shared-dir